import numpy as np

''' Simulation constants '''
TIME_STEPS = 2000
TICKS_PER_SEC = 1000
NUM_GENERATIONS = 1
POPULATION_SIZE = 1

''' Robot constants '''
NUM_SENSOR_NEURONS = 9
NUM_MOTOR_NEURONS = 12
START_NUM_MUTATIONS = 5
MAX_JOINT_FORCE = 40
JOINT_MOTOR_RANGE = 0.2
